name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: secrets 
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PWD: ${{ secrets.DOCKER_PWD }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag python-helloworld
    - name: tag the image
      run: docker tag python-helloworld jcnimi/python-helloworld:v1.0.0
    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PWD
    - name: docker push
      run: docker push jcnimi/python-helloworld:v1.0.0
      
      
